version: '3'
services:
  front-image:
    build:
      context: .
    container_name: front-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx 설정 파일
      - /etc/letsencrypt/archive/inkyuinst.store/fullchain1.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/archive/inkyuinst.store/privkey1.pem:/etc/ssl/private/privkey.pem:ro
